join(df_RLTNSHPas(RLTNSHP), RLTNSHPACCT_ID == SCDSCD_ORG_ID);

where(trim(SCDSCD_ORG_TYPE_CD)==WAC);

where(SCDRLTD_SCD_ORG_TYPE_CDisin(GRP,CLNT,ASSN));

(trim(SCDRLTD_SCD_ORG_SOR_CD)as(RLTD_SCD_ORG_SOR_CD),trim(SCDRLTD_SCD_ORG_ID)as(RLTD_SCD_ORG_ID), trim(SCDSCD_ORG_ID)as(SCD_ORG_ID),trim(SCDRLTD_SCD_ORG_TYPE_CD)as(RLTD_SCD_ORG_TYPE_CD));

SCD1RLTD_SCD_ORG_ID);

( F3SGMNTN_ASSN_ID ,F3SGMNTN_CLNT_ID ,F3SGMNTN_GRP_ID ,F3SGMNTN_SUBGRP_ID ,F3EMPLR_DEPT_NBR ,F3FULLY_INSRD_CD ,F3GRP_STTS_CD ,F3HLTH_PROD_SRVC_TYPE_CD ,F3prod_id1as(prod_id);

SCD2RLTD_SCD_ORG_ID)( F3SGMNTN_ASSN_ID ,F3SGMNTN_CLNT_ID ,F3SGMNTN_GRP_ID ,F3SGMNTN_SUBGRP_ID ,F3EMPLR_DEPT_NBR ,F3FULLY_INSRD_CD ,F3GRP_STTS_CD ,F3HLTH_PROD_SRVC_TYPE_CD ,F3prod_id1as(prod_id);

SCD3RLTD_SCD_ORG_ID)( F3SGMNTN_ASSN_ID ,F3SGMNTN_CLNT_ID ,F3SGMNTN_GRP_ID ,F3SGMNTN_SUBGRP_ID ,F3EMPLR_DEPT_NBR ,F3FULLY_INSRD_CD ,F3GRP_STTS_CD ,F3HLTH_PROD_SRVC_TYPE_CD ,F3prod_id1as(prod_id);

srgACCT_ID,left_outer);

(F4ACCT_ID ,F4SGMNTN_ASSN_ID ,F4SGMNTN_CLNT_ID ,F4SGMNTN_GRP_ID ,F4SGMNTN_SUBGRP_ID ,F4EMPLR_DEPT_NBR ,F4FULLY_INSRD_CD ,F4GRP_STTS_CD ,F4HLTH_PROD_SRVC_TYPE_CD ,ORIG_HLTH_PROD_SRVC_TYPE_CD ,when(F4prod_idisin(,~01,~02,~03,~NA,~DV,UNK) || F4prod_idisNull,NA)otherwise(upper(trim(regexp_replace(F4prod_id,\\^, \\s))))as(prod_id);

CIIUtilitiesreadDFfromS3(aDataSrcCfg,frame5);

